### ISSUE TITLE
IPN PaymentTransactionCodeType doesn't contain "refund" value

### ISSUE THREAD

**Issue by natom-software** [paypal/merchant-sdk-java#23] opened 2015-03-23 14:20 UTC
There is a problem with the newest (2.13.117) version of merchant-sdk-java, more specifically with PaymentTransactionCodeType. 
Along with SOAP Envelope I get (as a part of IPN message)
```xml 
<TransactionType xsi:type="ebl:PaymentTransactionCodeType">refund</TransactionType>
```
but PaymentTransactionCodeType doesn't contain "refund" value so it causes error during processing. 
As I've figured out corresponding .NET library contains "refund" value, so please let me know when are you going to release fixed version for Java?

**Comment by juwlee** [comment] 2015-08-06 00:50
This is a duplicate of #26 .

**Closed by juwlee** 2015-08-06 00:50 UTC
Labels: bug, duplicate
